#!/usr/bin/env python3
# -*- python -*-

import sys

from extract import docx2xml

if __name__ == "__main__":
    import argparse

    DESCRIPTION = (
        "Files with .docx extension are actually zip files,"
        "and the main contents is stored in word/document.xml."
        'This script extracts "word/document.xml" from a docx file.'
    )
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument(
        "input",
        metavar="PATH_TO_DOCX",
        help="""Path to the docx file to be extracted.""",
    )
    parser.add_argument(
        "--output",
        metavar="PATH_TO_XML",
        default="-",
        help="""Path to the output xml file. If "-", write into stdout. The default is "-".""",
    )

    args = parser.parse_args(sys.argv[1:])
    xml = docx2xml(args.input)

    if args.output == "-":
        sys.stdout.write(xml)
    else:
        open(args.output, "w").write(xml)
